deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: NHDYMC6RdYcASuf7QPAQhbQVVWwFQZSy589PVce+0FAQe1Vna3PNnpPu7cqFdxIc2gpXzf8SM3gkok88g57yZLTItOPo5/COHY/opDax39s4LXbApRad8SR9H+H5pXmXx1jjqwy4I4ZxIfvxQBGHEYls4VbMjXzIU3zK9uF8+RmaDdOd9K1UGOla2wP1xNaT0uBfnS5rnNEvuKm2x1LCqQB+YK/OcopFzqcz+6+xJw4NjQZNUoHiEzdy5I4DqphhMo+/Pco+iVEIa0rHpRsJpe9qMt3Lg56/JWJbQrWwdxEhJeBksZ8tRgiGKb8YN6FLXtRLsH4v6M8wk7lkgMgpd9Mh9VhZ+x/CQ1jMH+N2/8KbeCJcaVKc/fgPspc4Ava0QHMeAKndQw16oSHE0RMp8LYKwRdq5KWsdtuWczOIhMqyu1aF/o5AIo3pJkgsm1YCMmxeVLJYnltkjEMFhxPdAIL7HqNE6uIr9SdajZcHtUYH3D2gw3mqwhwtJsJng+YHZYdA+PUA0Sm69sd5vGrOnzAiADZknkjBS283Rvl6A4AANB53nVGZrJrX/40wBe+57q0qADkzg+G5JsjP2vg1J8CQ3abNiL+gIf5hPCwWGuyW4m7P2AAIomXB0xeeRJEYCR8Q3JnKBSoPyZKfld8A5O+nEgeIY4PbZ1KwlCqBCcY=
  on:
    tags: true
  skip_existing: true
install: pip install -U tox-travis
language: python
matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - env: TOXENV=flake8
    os: linux
    python: 3.6
script: tox
